# Set the background opacity under the 'window' section
[window]
  opacity = 0.5  # Adjust opacity here (0.0 is fully transparent, 1.0 is fully opaque)

# Font configurations
[font]
  normal.family = "JetBrains Mono Nerd Font"
  normal.style = "Regular"

  bold.family = "JetBrains Mono Nerd Font"
  bold.style = "Bold"

  italic.family = "JetBrains Mono Nerd Font"
  italic.style = "Italic"

  size = 9.5


[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# (Tokyo_night_eh) Colors for Alacritty

[colors.primary]
background = "#08080b"
foreground = "#787c99"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"
